export const prerender = false;

import type { APIRoute } from 'astro';
import { userHasRole } from '../../../../../lib/auth/session';
import { ensureShareToken, revokeShareToken } from '../../../../../lib/share-link';
import { logActivity } from '../../../../../lib/notify';

export const POST: APIRoute = async ({ request, locals, redirect }) => {
  const user = locals.user;
  if (!user || (!userHasRole(user, 'ADMIN') && !userHasRole(user, 'SUPER_ADMIN'))) {
    return redirect('/portal/login');
  }

  const data = await request.formData();
  const projectId = String(data.get('projectId') || '');
  const action = String(data.get('action') || 'generate');

  if (action === 'revoke') {
    await revokeShareToken(projectId);
    await logActivity(projectId, 'Client share link revoked by admin');
  } else {
    await ensureShareToken(projectId);
    await logActivity(projectId, 'Client share link generated by admin');
  }

  return redirect(`/portal/admin/projects/${projectId}`);
};
